name: Terraform Destroy

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: devops/terraform

    env:
      AWS_REGION: us-east-1

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - run: terraform init -upgrade

      - name: Terraform Destroy
        env:
          TF_VAR_datadog_api_key: ${{ secrets.DATADOG_API_KEY }}
          TF_VAR_datadog_app_key: ${{ secrets.DATADOG_APP_KEY }}
        run: terraform destroy -auto-approve