apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
spec:
  backoffLimit: 1

  template:
    spec:
      restartPolicy: Never

      containers:
        - name: db-migration
          image: 391701072873.dkr.ecr.us-east-1.amazonaws.com/db-migration:latest
          imagePullPolicy: Always

          command: ["/bin/sh", "-c"]
          args:
            - |
              set -e

              echo "Fetching DB credentials..."

              SECRET=$(aws secretsmanager get-secret-value \
                --secret-id $DB_SECRET_ARN \
                --region $AWS_REGION \
                --query SecretString \
                --output text)

              DB_USER=$(echo $SECRET | jq -r .username)
              DB_PASS=$(echo $SECRET | jq -r .password)

              echo "Fetching RDS endpoint..."

              DB_HOST=$(aws rds describe-db-instances \
                --region $AWS_REGION \
                --query "DBInstances[0].Endpoint.Address" \
                --output text)

              DB_NAME="demodb"
              DB_PORT=3306

              echo "Running Flyway migration..."

              flyway \
                -url=jdbc:mysql://$DB_HOST:$DB_PORT/$DB_NAME \
                -user=$DB_USER \
                -password=$DB_PASS \
                -locations=filesystem:/flyway/sql \
                migrate

              echo "Migration complete"

          env:
            - name: DB_SECRET_ARN
              value: "rds!db-d04bd647-c31d-4d00-85d1-0f9e4b230020"
            - name: AWS_REGION
              value: "us-east-1"