name: Build Prompt Gemini

on:
  push:
    branches:
      - main
    paths:
      - "devops/helm/prompt-gemini/**"
      - "microservices/prompt-gemini/**"
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build-prompt-gemini:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      ECR_REPO: 391701072873.dkr.ecr.us-east-1.amazonaws.com/prompt-gemini

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION \
          | docker login --username AWS --password-stdin 391701072873.dkr.ecr.us-east-1.amazonaws.com

      - name: Build image
        run: |
          docker build -t prompt-gemini microservices/prompt-gemini

      - name: Tag image
        run: |
          docker tag prompt-gemini:latest $ECR_REPO:latest

      - name: Push image
        run: |
          docker push $ECR_REPO:latest