name: Deploy Prompt Gemini

on:
  workflow_run:
    workflows: ["Build Prompt Gemini"]
    types:
      - completed

permissions:
  contents: read
  id-token: write

jobs:
  deploy-prompt-gemini:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      CLUSTER_NAME: demo-eks
      RELEASE_NAME: prompt-gemini
      NAMESPACE: prompt-gemini

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install kubectl
        run: |
          curl -LO https://dl.k8s.io/release/v1.29.0/bin/linux/amd64/kubectl
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Configure kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region $AWS_REGION \
            --name $CLUSTER_NAME

      - name: Deploy prompt-gemini (Helm)
        run: |
          helm upgrade --install $RELEASE_NAME devops/helm/prompt-gemini \
            --namespace $NAMESPACE \
            --create-namespace