name: Deploy Datadog

on:
  push:
    branches:
      - main
    paths:
      - "devops/helm/datadog/**"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy-datadog:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      CLUSTER_NAME: demo-eks

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install kubectl
        run: |
          curl -LO https://dl.k8s.io/release/v1.29.0/bin/linux/amd64/kubectl
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Configure kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region $AWS_REGION \
            --name $CLUSTER_NAME

      - name: Add Datadog repo
        run: |
          helm repo add datadog https://helm.datadoghq.com
          helm repo update

      - name: Deploy Datadog
        run: |
          helm upgrade --install datadog-agent datadog/datadog \
            --namespace datadog \
            --create-namespace \
            --set datadog.site=us5.datadoghq.com \
            --set datadog.clusterName=demo-eks \
            --set datadog.logs.enabled=true \
            --set datadog.logs.containerCollectAll=true \
            --set datadog.apm.enabled=true \
            --set datadog.processAgent.enabled=true \
            --set datadog.kubeStateMetricsEnabled=true \
            --set datadog.orchestratorExplorer.enabled=true \
            --set datadog.systemProbe.enabled=false \
            --set datadog.networkMonitoring.enabled=false